## Make sure passwords for database and logins match, Bad habit of not checking.
version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    image: order-management-backend
    environment:
      # Update the datasource URL to use the container name "postgres"
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/orderdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
